name: action-test

on:
  push:
    tags:
      - v*.*.*-alpha

env:
  APP_NAME: open_tree_hole_backend

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag version
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      
      - name: Build
        id: build
        run: echo "${{ steps.tag.outputs.tag }}"
